# Generated by Django 5.1.15 on 2026-03-08 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('organizations', '0001_initial'),
        ('requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('CREATED', 'Created'), ('VOLUNTEER_ASSIGNED', 'Volunteer Assigned'), ('PICKUP_IN_PROGRESS', 'Pickup In Progress'), ('ON_ROUTE', 'On Route'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='CREATED', max_length=30)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('donation_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='donations.donationcard')),
                ('donor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_missions', to=settings.AUTH_USER_MODEL)),
                ('receiver_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_missions', to='organizations.organization')),
                ('requirement_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='requirements.requirementcard')),
                ('volunteer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_missions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MissionEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('NGO_SELECTED', 'NGO Selected'), ('VOLUNTEER_ASSIGNED', 'Volunteer Assigned'), ('PICKUP_QR_GENERATED', 'Pickup QR Generated'), ('PICKUP_SCANNED', 'Pickup Scanned'), ('DELIVERY_QR_GENERATED', 'Delivery QR Generated'), ('DELIVERY_SCANNED', 'Delivery Scanned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='missions.mission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionQRToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_type', models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], max_length=20)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='missions.mission')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_qr_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['state'], name='missions_mi_state_20d792_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['created_at'], name='missions_mi_created_7d4c57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='missionqrtoken',
            unique_together={('mission', 'qr_type', 'is_active')},
        ),
    ]
