# Generated by Django 5.1.15 on 2026-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_pending_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('REQUESTED', 'Volunteer Requested'), ('VOLUNTEER_ASSIGNED', 'Volunteer Assigned'), ('PICKUP_IN_PROGRESS', 'Pickup In Progress'), ('ON_ROUTE', 'On Route'), ('DELIVERED', 'Delivered'), ('DELIVERY_PENDING', 'Delivery Pending'), ('DELIVERY_REJECTED', 'Delivery Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='missionevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('NGO_SELECTED', 'NGO Selected'), ('VOLUNTEER_REQUESTED', 'Volunteer Requested'), ('VOLUNTEER_REJECTED', 'Volunteer Rejected'), ('VOLUNTEER_ASSIGNED', 'Volunteer Assigned'), ('PICKUP_QR_GENERATED', 'Pickup QR Generated'), ('PICKUP_SCANNED', 'Pickup Scanned'), ('DELIVERY_VERIFY_REQUESTED', 'Delivery Verification Requested'), ('DELIVERY_REJECTED', 'Delivery Rejected'), ('DELIVERY_CONFIRMED', 'Delivery Confirmed'), ('DELIVERY_QR_GENERATED', 'Delivery QR Generated'), ('DELIVERY_SCANNED', 'Delivery Scanned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=40),
        ),
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_address', models.CharField(max_length=255, unique=True)),
                ('original_address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('provider', models.CharField(default='nominatim', max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['normalized_address'], name='missions_ge_normali_04d5b0_idx')],
            },
        ),
    ]
