# Generated by Django 5.1.15 on 2026-03-08 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiary_count', models.PositiveIntegerField(default=0)),
                ('public_note', models.CharField(blank=True, max_length=255)),
                ('photo_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_entry', to='missions.mission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
