# Generated by Django 5.1.15 on 2026-04-26 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household_size', models.PositiveIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HungerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_hunger_score', models.FloatField(default=0.0)),
                ('hours_since_last_delivery', models.FloatField(default=0.0)),
                ('household_size', models.PositiveIntegerField(default=1)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hunger_score', to='accounts.receiverprofile')),
            ],
            options={
                'ordering': ['-current_hunger_score'],
            },
        ),
    ]
