# Generated by Codex on 2026-04-26

from django.db import migrations


def backfill_receiver_profiles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    ReceiverProfile = apps.get_model('accounts', 'ReceiverProfile')
    HungerScore = apps.get_model('accounts', 'HungerScore')

    for user in User.objects.filter(role='RECEIVER'):
        receiver_profile, _ = ReceiverProfile.objects.get_or_create(
            user=user,
            defaults={'household_size': 1},
        )
        HungerScore.objects.get_or_create(
            receiver_profile=receiver_profile,
            defaults={'household_size': receiver_profile.household_size},
        )


def reverse_backfill_receiver_profiles(apps, schema_editor):
    # Preserve user data on rollback.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_receiverprofile_hungerscore'),
    ]

    operations = [
        migrations.RunPython(backfill_receiver_profiles, reverse_backfill_receiver_profiles),
    ]
