# Generated by Django 5.1.15 on 2026-03-08 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('food_title', models.CharField(max_length=120)),
                ('food_quantity', models.PositiveIntegerField()),
                ('quantity_unit', models.CharField(default='Meals', max_length=30)),
                ('food_category', models.CharField(choices=[('COOKED_MEALS', 'Cooked Meals'), ('DRY_RATIONS', 'Dry Rations'), ('BAKERY', 'Bakery'), ('PRODUCE', 'Produce'), ('OTHER', 'Other')], max_length=30)),
                ('expiry_time', models.DateTimeField()),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('image_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donation_cards', to=settings.AUTH_USER_MODEL)),
                ('donor_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_cards', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonationSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='donations.donationcard')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_suggestions', to='organizations.organization')),
            ],
            options={
                'ordering': ['distance_km'],
                'unique_together': {('donation', 'ngo')},
            },
        ),
    ]
