# Generated by Django 5.1.15 on 2026-03-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcard',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
